name: Check kubectl Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  check-kubectl-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      run: |
        KUBECTL_VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
        echo "Latest kubectl version: $KUBECTL_VERSION"
        echo "::set-output name=kubectl_version::$KUBECTL_VERSION"
      id: kubectl